export const VERIFICATION_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  REJECTED: 'REJECTED',
  PARTIALLY_VERIFIED: 'PARTIALLY_VERIFIED'
};

export const ENVIRONMENT = {
  LIVE: 'LIVE',
  SANDBOX: 'SANDBOX'
};
